chore: add action to close issues
DevExpress/devextreme-reactive pull request #3516
Opened 2022-02-14 16:16 UTC by Krijovnick

2022-02-15 09:28 UTC, MikeVitik approved these changes

2022-02-24 08:59 UTC, AnnaKondratova requested changes

2022-02-24 08:59 UTC, AnnaKondratova commented on .github/workflows/close-issues.yml
> +          We use GitHub issues exclusively as a bug and feature requests tracker.
```suggestion
          We use **GitHub issues** to track bug and feature requests.
```

2022-02-24 08:59 UTC, AnnaKondratova commented on .github/workflows/close-issues.yml
> +          We answer support questions as far as possible and if they are not active for 30 days, they are closed.
```suggestion
          We process incoming issues as soon as possible. Issues that have been inactive for 30 days are closed.
```

2022-02-24 08:59 UTC, AnnaKondratova commented on .github/workflows/close-issues.yml
> +          If you own an active DevExtreme license, feel free to contact us in the Support Center (https://www.devexpress.com/ask) to receive an answer shortly.
```suggestion
          If you have an active DevExtreme license, you can contact us in our [Support Center](https://www.devexpress.com/ask) for updates.
```

2022-02-24 08:59 UTC, AnnaKondratova commented on .github/workflows/close-issues.yml
> +          Otherwise post your question on StackOverflow."
```suggestion
          Otherwise, post your question on StackOverflow."
```

2022-02-24 09:02 UTC, AnnaKondratova approved these changes

2022-02-24 09:46 UTC, merged