chore: change text in contributing file
DevExpress/devextreme-reactive pull request #3524
Opened 2022-02-17 14:30 UTC by Krijovnick

2022-02-21 08:23 UTC, AnnaKondratova requested changes

2022-02-21 08:23 UTC, AnnaKondratova commented on CONTRIBUTING.md
> +## Bugs and Feature Requests
```suggestion
## Bug and Feature Requests
```

2022-02-21 08:23 UTC, AnnaKondratova commented on CONTRIBUTING.md
> +If you found a bug or want to request a feature, please submit an issue to our repository. You should check the list of active issues first to avoid duplicates.
```suggestion
Submit an issue to request a feature or report a bug. Check the list of active issues first to avoid duplicates.
```

2022-02-21 08:23 UTC, AnnaKondratova commented on CONTRIBUTING.md
> +If you are using DevExtreme Reactive under the DevExtreme Non-Commercial license, please refer to Stack Overflow for support. If you are the owner of an active commercial license, create a ticket in
```suggestion
Create a ticket in our [Support Center](https://www.devexpress.com/ask) if you own an active commercial license for DevExtreme Reactive. If you have a non-commercial license, refer to Stack Overflow for support.
```

2022-02-21 08:23 UTC, AnnaKondratova commented on README.md
> +See [Bugs and Feature Requests](https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md#bugs-and-feature-requests) and [Help and Support](https://github.com/DevExpress/devextrem
```suggestion
- [Bugs and Feature Requests](https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md#bugs-and-feature-requests) 
- [Help and Support](https://github.com/DevExpress/devextreme-reactive/blob/master/CONTRIBUTING.md#help-and-support)
```

2022-02-21 09:10 UTC, AnnaKondratova approved these changes

2022-02-24 08:04 UTC, MikeVitik approved these changes

2022-02-24 09:19 UTC, merged