fix(react-core): fix dragging on unmount component (T1093143)
DevExpress/devextreme-reactive pull request #3552
Opened 2022-06-06 13:12 UTC by Krijovnick

2022-06-07 08:07 UTC, MikeVitik requested changes

2022-06-07 08:07 UTC, MikeVitik commented on packages/dx-react-core/src/draggable.tsx
>    }
change name to isMouseEvent

2022-06-07 08:07 UTC, MikeVitik commented on packages/dx-react-core/src/draggable.tsx
>          break;
this.eventParams = null

2022-06-11 08:12 UTC, MikeVitik approved these changes

2022-06-16 10:37 UTC, groshenkovamarina approved these changes

2022-06-16 10:37 UTC, merged