chore: update ts
DevExpress/devextreme-reactive pull request #3590
Opened 2022-11-01 15:09 UTC by Krijovnick

2022-11-02 08:25 UTC, MikeVitik requested changes

2022-11-02 08:25 UTC, MikeVitik commented on packages/dx-react-core/src/ref-holder.tsx
> +      ? React.cloneElement(children as React.ReactElement<any>, { ref })
Is it possible to replcae
 children: React.ReactNode 
by 
children: React.ReactElement<any>

2022-11-02 08:25 UTC, MikeVitik commented on packages/dx-scheduler-core/src/constants.ts
>  export const WEEK_DAY_OPTIONS = { weekday: 'short' };
Why this const isn't as const?

2022-11-03 08:15 UTC, dxvladislavvolkov approved these changes

2022-11-03 08:34 UTC, MikeVitik approved these changes

2022-11-03 08:39 UTC, timbset approved these changes

2022-11-03 08:46 UTC, merged